### ISSUE TITLE
How can I do a PR from a non-forked

### ISSUE THREAD

**Issue by dedayoa** [Star2Billing/django-country-dialcode#7]
Some months back, I believe I tried to fix a few issues with django-country-dialcode. Seems the github repo was at 0.5.1 while the PyPi version was at 0.6.3.
Because a fork got me 0.5.1, I decided to download the PyPi archive and create https://github.com/dedayoa/django-country-dialcode/commits/master from it. Now, I'd like to contrib back to the original, but I'm guessing because this is not a "fork", the PR button won't activate.

Is there a way around this?

NB: According to https://github.com/Star2Billing/django-country-dialcode/blob/develop/country_dialcode/__init__.py, the github repo is still version 0.5.1

**Comment by areski** [comment]
I forgot to push some of the last code upstream.
Now it's fixed https://github.com/Star2Billing/django-country-dialcode/commits/develop, thanks!
